#ifndef KASOUZA_CCRAFT_INCLUDE_CCRAFT_ENGINE_INCLUDE_CCRAFT_ENGINE_DIRECTION_H
#define KASOUZA_CCRAFT_INCLUDE_CCRAFT_ENGINE_INCLUDE_CCRAFT_ENGINE_DIRECTION_H

enum CCRAFTE_Direction {
    CCRAFTE_DIRECTION_FORWARD,
    CCRAFTE_DIRECTION_BACKWARD,
    CCRAFTE_DIRECTION_LEFT,
    CCRAFTE_DIRECTION_RIGHT,
    CCRAFTE_DIRECTION_UPWARD,
    CCRAFTE_DIRECTION_DOWNWARD,
};

#endif
