#ifndef KASOUZA_CCRAFT_ENGINE_INCLUDE_KGL_ERROR_H
#define KASOUZA_CCRAFT_ENGINE_INCLUDE_KGL_ERROR_H

enum CCRAFTE_Error
{
    CCRAFTE_SUCCESS,	// Success == 0

    CCRAFTE_ERROR_GLFW_INIT,
    CCRAFTE_ERROR_WINDOW_CREATION,
    CCRAFTE_ERROR_GL_LOAD,
    CCRAFTE_ERROR_PROGRAM_CREATION,
    CCRAFTE_ERROR_FRAMEBUFFER_CREATION,

	CCRAFTE_ERROR_LAST,	// Used to create arrays
};

const char *CCRAFTE_get_error_message(enum CCRAFTE_Error error);

#endif
