#ifndef KASOUZA_INCLUDE_CCRAFT_ENGINE_INPUT_H
#define KASOUZA_INCLUDE_CCRAFT_ENGINE_INPUT_H

#include "ccraft/engine/vec2.h"

#include <stdbool.h>

enum CCRAFTE_Key
{
    CCRAFTE_KEY_UNKNOWN = -1,
    CCRAFTE_KEY_SPACE,
    CCRAFTE_KEY_APOSTROPHE,
    CCRAFTE_KEY_COMMA,
    CCRAFTE_KEY_MINUS,
    CCRAFTE_KEY_PERIOD,
    CCRAFTE_KEY_SLASH,
    CCRAFTE_KEY_0,
    CCRAFTE_KEY_1,
    CCRAFTE_KEY_2,
    CCRAFTE_KEY_3,
    CCRAFTE_KEY_4,
    CCRAFTE_KEY_5,
    CCRAFTE_KEY_6,
    CCRAFTE_KEY_7,
    CCRAFTE_KEY_8,
    CCRAFTE_KEY_9,
    CCRAFTE_KEY_SEMICOLON,
    CCRAFTE_KEY_EQUAL,
    CCRAFTE_KEY_A,
    CCRAFTE_KEY_B,
    CCRAFTE_KEY_C,
    CCRAFTE_KEY_D,
    CCRAFTE_KEY_E,
    CCRAFTE_KEY_F,
    CCRAFTE_KEY_G,
    CCRAFTE_KEY_H,
    CCRAFTE_KEY_I,
    CCRAFTE_KEY_J,
    CCRAFTE_KEY_K,
    CCRAFTE_KEY_L,
    CCRAFTE_KEY_M,
    CCRAFTE_KEY_N,
    CCRAFTE_KEY_O,
    CCRAFTE_KEY_P,
    CCRAFTE_KEY_Q,
    CCRAFTE_KEY_R,
    CCRAFTE_KEY_S,
    CCRAFTE_KEY_T,
    CCRAFTE_KEY_U,
    CCRAFTE_KEY_V,
    CCRAFTE_KEY_W,
    CCRAFTE_KEY_X,
    CCRAFTE_KEY_Y,
    CCRAFTE_KEY_Z,
    CCRAFTE_KEY_LEFT_BRACKET,
    CCRAFTE_KEY_BACKSLASH,
    CCRAFTE_KEY_RIGHT_BRACKET,
    CCRAFTE_KEY_GRAVE_ACCENT,
    CCRAFTE_KEY_WORLD_1,
    CCRAFTE_KEY_WORLD_2,
    CCRAFTE_KEY_ESCAPE,
    CCRAFTE_KEY_ENTER,
    CCRAFTE_KEY_TAB,
    CCRAFTE_KEY_BACKSPACE,
    CCRAFTE_KEY_INSERT,
    CCRAFTE_KEY_DELETE,
    CCRAFTE_KEY_RIGHT,
    CCRAFTE_KEY_LEFT,
    CCRAFTE_KEY_DOWN,
    CCRAFTE_KEY_UP,
    CCRAFTE_KEY_PAGE_UP,
    CCRAFTE_KEY_PAGE_DOWN,
    CCRAFTE_KEY_HOME,
    CCRAFTE_KEY_END,
    CCRAFTE_KEY_CAPS_LOCK,
    CCRAFTE_KEY_SCROLL_LOCK,
    CCRAFTE_KEY_NUM_LOCK,
    CCRAFTE_KEY_PRINT_SCREEN,
    CCRAFTE_KEY_PAUSE,
    CCRAFTE_KEY_F1,
    CCRAFTE_KEY_F2,
    CCRAFTE_KEY_F3,
    CCRAFTE_KEY_F4,
    CCRAFTE_KEY_F5,
    CCRAFTE_KEY_F6,
    CCRAFTE_KEY_F7,
    CCRAFTE_KEY_F8,
    CCRAFTE_KEY_F9,
    CCRAFTE_KEY_F10,
    CCRAFTE_KEY_F11,
    CCRAFTE_KEY_F12,
    CCRAFTE_KEY_F13,
    CCRAFTE_KEY_F14,
    CCRAFTE_KEY_F15,
    CCRAFTE_KEY_F16,
    CCRAFTE_KEY_F17,
    CCRAFTE_KEY_F18,
    CCRAFTE_KEY_F19,
    CCRAFTE_KEY_F20,
    CCRAFTE_KEY_F21,
    CCRAFTE_KEY_F22,
    CCRAFTE_KEY_F23,
    CCRAFTE_KEY_F24,
    CCRAFTE_KEY_F25,
    CCRAFTE_KEY_KP_0,
    CCRAFTE_KEY_KP_1,
    CCRAFTE_KEY_KP_2,
    CCRAFTE_KEY_KP_3,
    CCRAFTE_KEY_KP_4,
    CCRAFTE_KEY_KP_5,
    CCRAFTE_KEY_KP_6,
    CCRAFTE_KEY_KP_7,
    CCRAFTE_KEY_KP_8,
    CCRAFTE_KEY_KP_9,
    CCRAFTE_KEY_KP_DECIMAL,
    CCRAFTE_KEY_KP_DIVIDE,
    CCRAFTE_KEY_KP_MULTIPLY,
    CCRAFTE_KEY_KP_SUBTRACT,
    CCRAFTE_KEY_KP_ADD,
    CCRAFTE_KEY_KP_ENTER,
    CCRAFTE_KEY_KP_EQUAL,
    CCRAFTE_KEY_LEFT_SHIFT,
    CCRAFTE_KEY_LEFT_CONTROL,
    CCRAFTE_KEY_LEFT_ALT,
    CCRAFTE_KEY_LEFT_SUPER,
    CCRAFTE_KEY_RIGHT_SHIFT,
    CCRAFTE_KEY_RIGHT_CONTROL,
    CCRAFTE_KEY_RIGHT_ALT,
    CCRAFTE_KEY_RIGHT_SUPER,
    CCRAFTE_KEY_MENU,
    CCRAFTE_KEY_LAST,
};

enum CCRAFTE_MouseButton
{
    CCRAFTE_MOUSE_BUTTON_NONE,
    CCRAFTE_MOUSE_BUTTON_1,
    CCRAFTE_MOUSE_BUTTON_2,
    CCRAFTE_MOUSE_BUTTON_3,
    CCRAFTE_MOUSE_BUTTON_4,
    CCRAFTE_MOUSE_BUTTON_5,
    CCRAFTE_MOUSE_BUTTON_6,
    CCRAFTE_MOUSE_BUTTON_7,
    CCRAFTE_MOUSE_BUTTON_8,
    CCRAFTE_MOUSE_BUTTON_LAST,
};

enum CCRAFTE_InputAction
{
    CCRAFTE_PRESS,
    CCRAFTE_RELEASE,
};

struct CCRAFTE_Mouse {
    union CCRAFTE_Vec2 position;

    double scroll_offset_x;
    double scroll_offset_y;
    bool scrolling;

    bool buttons[CCRAFTE_MOUSE_BUTTON_LAST];
};

struct CCRAFTE_Keyboard {
    bool keys[CCRAFTE_KEY_LAST];
};

const struct CCRAFTE_Mouse *CCRAFTE_get_mouse();
const struct CCRAFTE_Keyboard *CCRAFTE_get_keyboard();

// Used internally, no need to call it yourself
void CCRAFTE_input_init();
void CCRAFTE_input_update();

bool CCRAFTE_is_key_pressed(enum CCRAFTE_Key key);
union CCRAFTE_Vec2 CCRAFTE_get_mouse_position();

#endif
