#ifndef KASOUZA_CCRAFT_INCLUDE_CCRAFT_ENGINE_INCLUDE_CCRAFT_ENGINE_MATH_H
#define KASOUZA_CCRAFT_INCLUDE_CCRAFT_ENGINE_INCLUDE_CCRAFT_ENGINE_MATH_H

#include <math.h>

#define CCRAFTE_RADIANS(deg) (deg * M_PI / 180)

#endif
