#include "ccraft/engine/input.h"
#include "ccraft/engine/gl_includes.h"
#include "ccraft/engine/renderer.h"
#include "ccraft/engine/utils.h"

#include <assert.h>
#include <stdbool.h>

static struct CCRAFTE_Mouse {
    double x;
    double y;

    double scroll_offset_x;
    double scroll_offset_y;
    bool scrolling;

    bool buttons[CCRAFTE_MOUSE_BUTTON_LAST];
} s_mouse = {0};

static struct CCRAFTE_Keyboard {
    bool keys[CCRAFTE_KEY_LAST];
} s_keyboard = {0};

// These arrays here map the keys/button/actions this library API provides to
// the keys/butotn/actions used internally (in this case, provided by GLFW)
/*static int box_keys_to_glfw_keys[] = {*/
/*[CCRAFTE_KEY_SPACE] = GLFW_KEY_SPACE,*/
/*[CCRAFTE_KEY_APOSTROPHE] = GLFW_KEY_APOSTROPHE,*/
/*[CCRAFTE_KEY_COMMA] = GLFW_KEY_COMMA,*/
/*[CCRAFTE_KEY_MINUS] = GLFW_KEY_MINUS,*/
/*[CCRAFTE_KEY_PERIOD] = GLFW_KEY_PERIOD,*/
/*[CCRAFTE_KEY_SLASH] = GLFW_KEY_SLASH,*/
/*[CCRAFTE_KEY_0] = GLFW_KEY_0,*/
/*[CCRAFTE_KEY_1] = GLFW_KEY_1,*/
/*[CCRAFTE_KEY_2] = GLFW_KEY_2,*/
/*[CCRAFTE_KEY_3] = GLFW_KEY_3,*/
/*[CCRAFTE_KEY_4] = GLFW_KEY_4,*/
/*[CCRAFTE_KEY_5] = GLFW_KEY_5,*/
/*[CCRAFTE_KEY_6] = GLFW_KEY_6,*/
/*[CCRAFTE_KEY_7] = GLFW_KEY_7,*/
/*[CCRAFTE_KEY_8] = GLFW_KEY_8,*/
/*[CCRAFTE_KEY_9] = GLFW_KEY_9,*/
/*[CCRAFTE_KEY_SEMICOLON] = GLFW_KEY_SEMICOLON,*/
/*[CCRAFTE_KEY_EQUAL] = GLFW_KEY_EQUAL,*/
/*[CCRAFTE_KEY_A] = GLFW_KEY_A,*/
/*[CCRAFTE_KEY_B] = GLFW_KEY_B,*/
/*[CCRAFTE_KEY_C] = GLFW_KEY_C,*/
/*[CCRAFTE_KEY_D] = GLFW_KEY_D,*/
/*[CCRAFTE_KEY_E] = GLFW_KEY_E,*/
/*[CCRAFTE_KEY_F] = GLFW_KEY_F,*/
/*[CCRAFTE_KEY_G] = GLFW_KEY_G,*/
/*[CCRAFTE_KEY_H] = GLFW_KEY_H,*/
/*[CCRAFTE_KEY_I] = GLFW_KEY_I,*/
/*[CCRAFTE_KEY_J] = GLFW_KEY_J,*/
/*[CCRAFTE_KEY_K] = GLFW_KEY_K,*/
/*[CCRAFTE_KEY_L] = GLFW_KEY_L,*/
/*[CCRAFTE_KEY_M] = GLFW_KEY_M,*/
/*[CCRAFTE_KEY_N] = GLFW_KEY_N,*/
/*[CCRAFTE_KEY_O] = GLFW_KEY_O,*/
/*[CCRAFTE_KEY_P] = GLFW_KEY_P,*/
/*[CCRAFTE_KEY_Q] = GLFW_KEY_Q,*/
/*[CCRAFTE_KEY_R] = GLFW_KEY_R,*/
/*[CCRAFTE_KEY_S] = GLFW_KEY_S,*/
/*[CCRAFTE_KEY_T] = GLFW_KEY_T,*/
/*[CCRAFTE_KEY_U] = GLFW_KEY_U,*/
/*[CCRAFTE_KEY_V] = GLFW_KEY_V,*/
/*[CCRAFTE_KEY_W] = GLFW_KEY_W,*/
/*[CCRAFTE_KEY_X] = GLFW_KEY_X,*/
/*[CCRAFTE_KEY_Y] = GLFW_KEY_Y,*/
/*[CCRAFTE_KEY_Z] = GLFW_KEY_Z,*/
/*[CCRAFTE_KEY_LEFT_BRACKET] = GLFW_KEY_LEFT_BRACKET,*/
/*[CCRAFTE_KEY_BACKSLASH] = GLFW_KEY_BACKSLASH,*/
/*[CCRAFTE_KEY_RIGHT_BRACKET] = GLFW_KEY_RIGHT_BRACKET,*/
/*[CCRAFTE_KEY_GRAVE_ACCENT] = GLFW_KEY_GRAVE_ACCENT,*/
/*[CCRAFTE_KEY_WORLD_1] = GLFW_KEY_WORLD_1,*/
/*[CCRAFTE_KEY_WORLD_2] = GLFW_KEY_WORLD_2,*/
/*[CCRAFTE_KEY_ESCAPE] = GLFW_KEY_ESCAPE,*/
/*[CCRAFTE_KEY_ENTER] = GLFW_KEY_ENTER,*/
/*[CCRAFTE_KEY_TAB] = GLFW_KEY_TAB,*/
/*[CCRAFTE_KEY_BACKSPACE] = GLFW_KEY_BACKSPACE,*/
/*[CCRAFTE_KEY_INSERT] = GLFW_KEY_INSERT,*/
/*[CCRAFTE_KEY_DELETE] = GLFW_KEY_DELETE,*/
/*[CCRAFTE_KEY_RIGHT] = GLFW_KEY_RIGHT,*/
/*[CCRAFTE_KEY_LEFT] = GLFW_KEY_LEFT,*/
/*[CCRAFTE_KEY_DOWN] = GLFW_KEY_DOWN,*/
/*[CCRAFTE_KEY_UP] = GLFW_KEY_UP,*/
/*[CCRAFTE_KEY_PAGE_UP] = GLFW_KEY_PAGE_UP,*/
/*[CCRAFTE_KEY_PAGE_DOWN] = GLFW_KEY_PAGE_DOWN,*/
/*[CCRAFTE_KEY_HOME] = GLFW_KEY_HOME,*/
/*[CCRAFTE_KEY_END] = GLFW_KEY_END,*/
/*[CCRAFTE_KEY_CAPS_LOCK] = GLFW_KEY_CAPS_LOCK,*/
/*[CCRAFTE_KEY_SCROLL_LOCK] = GLFW_KEY_SCROLL_LOCK,*/
/*[CCRAFTE_KEY_NUM_LOCK] = GLFW_KEY_NUM_LOCK,*/
/*[CCRAFTE_KEY_PRINT_SCREEN] = GLFW_KEY_PRINT_SCREEN,*/
/*[CCRAFTE_KEY_PAUSE] = GLFW_KEY_PAUSE,*/
/*[CCRAFTE_KEY_F1] = GLFW_KEY_F1,*/
/*[CCRAFTE_KEY_F2] = GLFW_KEY_F2,*/
/*[CCRAFTE_KEY_F3] = GLFW_KEY_F3,*/
/*[CCRAFTE_KEY_F4] = GLFW_KEY_F4,*/
/*[CCRAFTE_KEY_F5] = GLFW_KEY_F5,*/
/*[CCRAFTE_KEY_F6] = GLFW_KEY_F6,*/
/*[CCRAFTE_KEY_F7] = GLFW_KEY_F7,*/
/*[CCRAFTE_KEY_F8] = GLFW_KEY_F8,*/
/*[CCRAFTE_KEY_F9] = GLFW_KEY_F9,*/
/*[CCRAFTE_KEY_F10] = GLFW_KEY_F10,*/
/*[CCRAFTE_KEY_F11] = GLFW_KEY_F11,*/
/*[CCRAFTE_KEY_F12] = GLFW_KEY_F12,*/
/*[CCRAFTE_KEY_F13] = GLFW_KEY_F13,*/
/*[CCRAFTE_KEY_F14] = GLFW_KEY_F14,*/
/*[CCRAFTE_KEY_F15] = GLFW_KEY_F15,*/
/*[CCRAFTE_KEY_F16] = GLFW_KEY_F16,*/
/*[CCRAFTE_KEY_F17] = GLFW_KEY_F17,*/
/*[CCRAFTE_KEY_F18] = GLFW_KEY_F18,*/
/*[CCRAFTE_KEY_F19] = GLFW_KEY_F19,*/
/*[CCRAFTE_KEY_F20] = GLFW_KEY_F20,*/
/*[CCRAFTE_KEY_F21] = GLFW_KEY_F21,*/
/*[CCRAFTE_KEY_F22] = GLFW_KEY_F22,*/
/*[CCRAFTE_KEY_F23] = GLFW_KEY_F23,*/
/*[CCRAFTE_KEY_F24] = GLFW_KEY_F24,*/
/*[CCRAFTE_KEY_F25] = GLFW_KEY_F25,*/
/*[CCRAFTE_KEY_KP_0] = GLFW_KEY_KP_0,*/
/*[CCRAFTE_KEY_KP_1] = GLFW_KEY_KP_1,*/
/*[CCRAFTE_KEY_KP_2] = GLFW_KEY_KP_2,*/
/*[CCRAFTE_KEY_KP_3] = GLFW_KEY_KP_3,*/
/*[CCRAFTE_KEY_KP_4] = GLFW_KEY_KP_4,*/
/*[CCRAFTE_KEY_KP_5] = GLFW_KEY_KP_5,*/
/*[CCRAFTE_KEY_KP_6] = GLFW_KEY_KP_6,*/
/*[CCRAFTE_KEY_KP_7] = GLFW_KEY_KP_7,*/
/*[CCRAFTE_KEY_KP_8] = GLFW_KEY_KP_8,*/
/*[CCRAFTE_KEY_KP_9] = GLFW_KEY_KP_9,*/
/*[CCRAFTE_KEY_KP_DECIMAL] = GLFW_KEY_KP_DECIMAL,*/
/*[CCRAFTE_KEY_KP_DIVIDE] = GLFW_KEY_KP_DIVIDE,*/
/*[CCRAFTE_KEY_KP_MULTIPLY] = GLFW_KEY_KP_MULTIPLY,*/
/*[CCRAFTE_KEY_KP_SUBTRACT] = GLFW_KEY_KP_SUBTRACT,*/
/*[CCRAFTE_KEY_KP_ADD] = GLFW_KEY_KP_ADD,*/
/*[CCRAFTE_KEY_KP_ENTER] = GLFW_KEY_KP_ENTER,*/
/*[CCRAFTE_KEY_KP_EQUAL] = GLFW_KEY_KP_EQUAL,*/
/*[CCRAFTE_KEY_LEFT_SHIFT] = GLFW_KEY_LEFT_SHIFT,*/
/*[CCRAFTE_KEY_LEFT_CONTROL] = GLFW_KEY_LEFT_CONTROL,*/
/*[CCRAFTE_KEY_LEFT_ALT] = GLFW_KEY_LEFT_ALT,*/
/*[CCRAFTE_KEY_LEFT_SUPER] = GLFW_KEY_LEFT_SUPER,*/
/*[CCRAFTE_KEY_RIGHT_SHIFT] = GLFW_KEY_RIGHT_SHIFT,*/
/*[CCRAFTE_KEY_RIGHT_CONTROL] = GLFW_KEY_RIGHT_CONTROL,*/
/*[CCRAFTE_KEY_RIGHT_ALT] = GLFW_KEY_RIGHT_ALT,*/
/*[CCRAFTE_KEY_RIGHT_SUPER] = GLFW_KEY_RIGHT_SUPER,*/
/*[CCRAFTE_KEY_MENU] = GLFW_KEY_MENU,*/
/*};*/

static int glfw_keys_to_CCRAFTE_keys[] = {
    [GLFW_KEY_SPACE] = CCRAFTE_KEY_SPACE,
    [GLFW_KEY_APOSTROPHE] = CCRAFTE_KEY_APOSTROPHE,
    [GLFW_KEY_COMMA] = CCRAFTE_KEY_COMMA,
    [GLFW_KEY_MINUS] = CCRAFTE_KEY_MINUS,
    [GLFW_KEY_PERIOD] = CCRAFTE_KEY_PERIOD,
    [GLFW_KEY_SLASH] = CCRAFTE_KEY_SLASH,
    [GLFW_KEY_0] = CCRAFTE_KEY_0,
    [GLFW_KEY_1] = CCRAFTE_KEY_1,
    [GLFW_KEY_2] = CCRAFTE_KEY_2,
    [GLFW_KEY_3] = CCRAFTE_KEY_3,
    [GLFW_KEY_4] = CCRAFTE_KEY_4,
    [GLFW_KEY_5] = CCRAFTE_KEY_5,
    [GLFW_KEY_6] = CCRAFTE_KEY_6,
    [GLFW_KEY_7] = CCRAFTE_KEY_7,
    [GLFW_KEY_8] = CCRAFTE_KEY_8,
    [GLFW_KEY_9] = CCRAFTE_KEY_9,
    [GLFW_KEY_SEMICOLON] = CCRAFTE_KEY_SEMICOLON,
    [GLFW_KEY_EQUAL] = CCRAFTE_KEY_EQUAL,
    [GLFW_KEY_A] = CCRAFTE_KEY_A,
    [GLFW_KEY_B] = CCRAFTE_KEY_B,
    [GLFW_KEY_C] = CCRAFTE_KEY_C,
    [GLFW_KEY_D] = CCRAFTE_KEY_D,
    [GLFW_KEY_E] = CCRAFTE_KEY_E,
    [GLFW_KEY_F] = CCRAFTE_KEY_F,
    [GLFW_KEY_G] = CCRAFTE_KEY_G,
    [GLFW_KEY_H] = CCRAFTE_KEY_H,
    [GLFW_KEY_I] = CCRAFTE_KEY_I,
    [GLFW_KEY_J] = CCRAFTE_KEY_J,
    [GLFW_KEY_K] = CCRAFTE_KEY_K,
    [GLFW_KEY_L] = CCRAFTE_KEY_L,
    [GLFW_KEY_M] = CCRAFTE_KEY_M,
    [GLFW_KEY_N] = CCRAFTE_KEY_N,
    [GLFW_KEY_O] = CCRAFTE_KEY_O,
    [GLFW_KEY_P] = CCRAFTE_KEY_P,
    [GLFW_KEY_Q] = CCRAFTE_KEY_Q,
    [GLFW_KEY_R] = CCRAFTE_KEY_R,
    [GLFW_KEY_S] = CCRAFTE_KEY_S,
    [GLFW_KEY_T] = CCRAFTE_KEY_T,
    [GLFW_KEY_U] = CCRAFTE_KEY_U,
    [GLFW_KEY_V] = CCRAFTE_KEY_V,
    [GLFW_KEY_W] = CCRAFTE_KEY_W,
    [GLFW_KEY_X] = CCRAFTE_KEY_X,
    [GLFW_KEY_Y] = CCRAFTE_KEY_Y,
    [GLFW_KEY_Z] = CCRAFTE_KEY_Z,
    [GLFW_KEY_LEFT_BRACKET] = CCRAFTE_KEY_LEFT_BRACKET,
    [GLFW_KEY_BACKSLASH] = CCRAFTE_KEY_BACKSLASH,
    [GLFW_KEY_RIGHT_BRACKET] = CCRAFTE_KEY_RIGHT_BRACKET,
    [GLFW_KEY_GRAVE_ACCENT] = CCRAFTE_KEY_GRAVE_ACCENT,
    [GLFW_KEY_WORLD_1] = CCRAFTE_KEY_WORLD_1,
    [GLFW_KEY_WORLD_2] = CCRAFTE_KEY_WORLD_2,
    [GLFW_KEY_ESCAPE] = CCRAFTE_KEY_ESCAPE,
    [GLFW_KEY_ENTER] = CCRAFTE_KEY_ENTER,
    [GLFW_KEY_TAB] = CCRAFTE_KEY_TAB,
    [GLFW_KEY_BACKSPACE] = CCRAFTE_KEY_BACKSPACE,
    [GLFW_KEY_INSERT] = CCRAFTE_KEY_INSERT,
    [GLFW_KEY_DELETE] = CCRAFTE_KEY_DELETE,
    [GLFW_KEY_RIGHT] = CCRAFTE_KEY_RIGHT,
    [GLFW_KEY_LEFT] = CCRAFTE_KEY_LEFT,
    [GLFW_KEY_DOWN] = CCRAFTE_KEY_DOWN,
    [GLFW_KEY_UP] = CCRAFTE_KEY_UP,
    [GLFW_KEY_PAGE_UP] = CCRAFTE_KEY_PAGE_UP,
    [GLFW_KEY_PAGE_DOWN] = CCRAFTE_KEY_PAGE_DOWN,
    [GLFW_KEY_HOME] = CCRAFTE_KEY_HOME,
    [GLFW_KEY_END] = CCRAFTE_KEY_END,
    [GLFW_KEY_CAPS_LOCK] = CCRAFTE_KEY_CAPS_LOCK,
    [GLFW_KEY_SCROLL_LOCK] = CCRAFTE_KEY_SCROLL_LOCK,
    [GLFW_KEY_NUM_LOCK] = CCRAFTE_KEY_NUM_LOCK,
    [GLFW_KEY_PRINT_SCREEN] = CCRAFTE_KEY_PRINT_SCREEN,
    [GLFW_KEY_PAUSE] = CCRAFTE_KEY_PAUSE,
    [GLFW_KEY_F1] = CCRAFTE_KEY_F1,
    [GLFW_KEY_F2] = CCRAFTE_KEY_F2,
    [GLFW_KEY_F3] = CCRAFTE_KEY_F3,
    [GLFW_KEY_F4] = CCRAFTE_KEY_F4,
    [GLFW_KEY_F5] = CCRAFTE_KEY_F5,
    [GLFW_KEY_F6] = CCRAFTE_KEY_F6,
    [GLFW_KEY_F7] = CCRAFTE_KEY_F7,
    [GLFW_KEY_F8] = CCRAFTE_KEY_F8,
    [GLFW_KEY_F9] = CCRAFTE_KEY_F9,
    [GLFW_KEY_F10] = CCRAFTE_KEY_F10,
    [GLFW_KEY_F11] = CCRAFTE_KEY_F11,
    [GLFW_KEY_F12] = CCRAFTE_KEY_F12,
    [GLFW_KEY_F13] = CCRAFTE_KEY_F13,
    [GLFW_KEY_F14] = CCRAFTE_KEY_F14,
    [GLFW_KEY_F15] = CCRAFTE_KEY_F15,
    [GLFW_KEY_F16] = CCRAFTE_KEY_F16,
    [GLFW_KEY_F17] = CCRAFTE_KEY_F17,
    [GLFW_KEY_F18] = CCRAFTE_KEY_F18,
    [GLFW_KEY_F19] = CCRAFTE_KEY_F19,
    [GLFW_KEY_F20] = CCRAFTE_KEY_F20,
    [GLFW_KEY_F21] = CCRAFTE_KEY_F21,
    [GLFW_KEY_F22] = CCRAFTE_KEY_F22,
    [GLFW_KEY_F23] = CCRAFTE_KEY_F23,
    [GLFW_KEY_F24] = CCRAFTE_KEY_F24,
    [GLFW_KEY_F25] = CCRAFTE_KEY_F25,
    [GLFW_KEY_KP_0] = CCRAFTE_KEY_KP_0,
    [GLFW_KEY_KP_1] = CCRAFTE_KEY_KP_1,
    [GLFW_KEY_KP_2] = CCRAFTE_KEY_KP_2,
    [GLFW_KEY_KP_3] = CCRAFTE_KEY_KP_3,
    [GLFW_KEY_KP_4] = CCRAFTE_KEY_KP_4,
    [GLFW_KEY_KP_5] = CCRAFTE_KEY_KP_5,
    [GLFW_KEY_KP_6] = CCRAFTE_KEY_KP_6,
    [GLFW_KEY_KP_7] = CCRAFTE_KEY_KP_7,
    [GLFW_KEY_KP_8] = CCRAFTE_KEY_KP_8,
    [GLFW_KEY_KP_9] = CCRAFTE_KEY_KP_9,
    [GLFW_KEY_KP_DECIMAL] = CCRAFTE_KEY_KP_DECIMAL,
    [GLFW_KEY_KP_DIVIDE] = CCRAFTE_KEY_KP_DIVIDE,
    [GLFW_KEY_KP_MULTIPLY] = CCRAFTE_KEY_KP_MULTIPLY,
    [GLFW_KEY_KP_SUBTRACT] = CCRAFTE_KEY_KP_SUBTRACT,
    [GLFW_KEY_KP_ADD] = CCRAFTE_KEY_KP_ADD,
    [GLFW_KEY_KP_ENTER] = CCRAFTE_KEY_KP_ENTER,
    [GLFW_KEY_KP_EQUAL] = CCRAFTE_KEY_KP_EQUAL,
    [GLFW_KEY_LEFT_SHIFT] = CCRAFTE_KEY_LEFT_SHIFT,
    [GLFW_KEY_LEFT_CONTROL] = CCRAFTE_KEY_LEFT_CONTROL,
    [GLFW_KEY_LEFT_ALT] = CCRAFTE_KEY_LEFT_ALT,
    [GLFW_KEY_LEFT_SUPER] = CCRAFTE_KEY_LEFT_SUPER,
    [GLFW_KEY_RIGHT_SHIFT] = CCRAFTE_KEY_RIGHT_SHIFT,
    [GLFW_KEY_RIGHT_CONTROL] = CCRAFTE_KEY_RIGHT_CONTROL,
    [GLFW_KEY_RIGHT_ALT] = CCRAFTE_KEY_RIGHT_ALT,
    [GLFW_KEY_RIGHT_SUPER] = CCRAFTE_KEY_RIGHT_SUPER,
    [GLFW_KEY_MENU] = CCRAFTE_KEY_MENU,
};

/*static int CCRAFTE_mouse_button_to_glfw_mouse_button[] = {*/
/*[CCRAFTE_MOUSE_BUTTON_1] = GLFW_MOUSE_BUTTON_1,*/
/*[CCRAFTE_MOUSE_BUTTON_2] = GLFW_MOUSE_BUTTON_2,*/
/*[CCRAFTE_MOUSE_BUTTON_3] = GLFW_MOUSE_BUTTON_3,*/
/*[CCRAFTE_MOUSE_BUTTON_4] = GLFW_MOUSE_BUTTON_4,*/
/*[CCRAFTE_MOUSE_BUTTON_5] = GLFW_MOUSE_BUTTON_5,*/
/*[CCRAFTE_MOUSE_BUTTON_6] = GLFW_MOUSE_BUTTON_6,*/
/*[CCRAFTE_MOUSE_BUTTON_7] = GLFW_MOUSE_BUTTON_7,*/
/*[CCRAFTE_MOUSE_BUTTON_8] = GLFW_MOUSE_BUTTON_8,*/
/*};*/

static int glfw_mouse_button_to_CCRAFTE_mouse_button[] = {
    [GLFW_MOUSE_BUTTON_1] = CCRAFTE_MOUSE_BUTTON_1,
    [GLFW_MOUSE_BUTTON_2] = CCRAFTE_MOUSE_BUTTON_2,
    [GLFW_MOUSE_BUTTON_3] = CCRAFTE_MOUSE_BUTTON_3,
    [GLFW_MOUSE_BUTTON_4] = CCRAFTE_MOUSE_BUTTON_4,
    [GLFW_MOUSE_BUTTON_5] = CCRAFTE_MOUSE_BUTTON_5,
    [GLFW_MOUSE_BUTTON_6] = CCRAFTE_MOUSE_BUTTON_6,
    [GLFW_MOUSE_BUTTON_7] = CCRAFTE_MOUSE_BUTTON_7,
    [GLFW_MOUSE_BUTTON_8] = CCRAFTE_MOUSE_BUTTON_8,
};

/*static int CCRAFTE_input_action_to_glfw_action[] = {*/
/*[CCRAFTE_PRESS] = GLFW_PRESS,*/
/*[CCRAFTE_RELEASE] = GLFW_RELEASE,*/
/*};*/

/*static int glfw_action_to_CCRAFTE_input_action[] = {*/
/*[GLFW_PRESS] = CCRAFTE_PRESS,*/
/*[GLFW_RELEASE] = CCRAFTE_RELEASE,*/
/*};*/

const struct CCRAFTE_Mouse *CCRAFTE_get_mouse() { return &s_mouse; }
const struct CCRAFTE_Keyboard *CCRAFTE_get_keyboard() { return &s_keyboard; }

void input_cursor_pos_cb(GLFWwindow *window, double x_pos, double y_pos) {
    CCRAFTE_UNUSED(window);

    s_mouse.x = x_pos;
    s_mouse.y = y_pos;
}

void input_key_cb(GLFWwindow *window, int key, int scancode, int action,
                  int mods) {
    CCRAFTE_UNUSED(window);
    CCRAFTE_UNUSED(scancode);
    CCRAFTE_UNUSED(mods);

    if (action == GLFW_PRESS) {
        s_keyboard.keys[glfw_keys_to_CCRAFTE_keys[key]] = true;
    }

    if (action == GLFW_RELEASE) {
        s_keyboard.keys[glfw_keys_to_CCRAFTE_keys[key]] = false;
    }
}

void mouse_button_callback(GLFWwindow *window, int button, int action,
                           int mods) {
    CCRAFTE_UNUSED(window);
    CCRAFTE_UNUSED(mods);

    if (action == GLFW_PRESS) {
        s_mouse.buttons[glfw_mouse_button_to_CCRAFTE_mouse_button[button]] =
            true;
    }

    if (action == GLFW_RELEASE) {
        s_mouse.buttons[glfw_mouse_button_to_CCRAFTE_mouse_button[button]] =
            false;
    }
}

void scroll_callback(GLFWwindow *window, double x_offset, double y_offset) {
    CCRAFTE_UNUSED(window);

    s_mouse.scroll_offset_x += x_offset;
    s_mouse.scroll_offset_y += y_offset;
    s_mouse.scrolling = true;
}

void CCRAFTE_input_init() {
    GLFWwindow *window = CCRAFTE_get_window();
    assert(window != NULL && "No window available for input handling.");

    glfwSetCursorPosCallback(window, input_cursor_pos_cb);
    glfwSetKeyCallback(window, input_key_cb);
    glfwSetMouseButtonCallback(window, mouse_button_callback);
    glfwSetScrollCallback(window, scroll_callback);
}

void CCRAFTE_input_update() {
    s_mouse.scroll_offset_x = 0;
    s_mouse.scroll_offset_y = 0;
    s_mouse.scrolling = false;
}
