#ifndef KASOUZA_CCRAFT_INCLUDE_CCRAFT_INCLUDE_CCRAFT_SIDE_H
#define KASOUZA_CCRAFT_INCLUDE_CCRAFT_INCLUDE_CCRAFT_SIDE_H

enum CCRAFT_Side {
    CCRAFT_SIDE_TOP,
    CCRAFT_SIDE_BOTTOM,

    CCRAFT_SIDE_LEFT,
    CCRAFT_SIDE_RIGHT,

    CCRAFT_SIDE_BACK,
    CCRAFT_SIDE_FRONT,

    CCRAFT_SIDE_LAST,
};

#endif
